# Generated by Django 5.1.1 on 2024-09-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0002_uploadedfile'),
    ]

    operations = [
 
    ]
