# Generated by Django 5.1.1 on 2024-09-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_uploadedfile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
